baseURL = "https://www.glintstream.com/"
languageCode = "en-us"
title = "blog.glintstream"
theme = "aether"

[params]
    brand = "blog.glintstream"
    description = "Thoughts of a Software Enthusiast"
    rssinmenu = true